version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ticketsmith_api
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
    volumes:
      - .:/app

  frontend:
    build:
      context: ./frontend
    container_name: ticketsmith_frontend
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
