version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ticketsmith_api
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
    volumes:
      - .:/app

  frontend:
    build:
      context: ./frontend
    container_name: ticketsmith_frontend
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true

  inference:
    build:
      context: .
      dockerfile: Dockerfile.vllm
    container_name: llm_inference
    ports:
      - "8000:8000"
    environment:
      - VLLM_MODEL=${VLLM_MODEL}
      - INFERENCE_API_KEY=${INFERENCE_API_KEY}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
